name: Update counters

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch: null

jobs:
  update-counters:
    runs-on: ubuntu-latest
    name: automerge
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install deps
        run: python -m pip install pygithub requests

      - name: Run script
        run: python scripts/live_counts.py
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}

      - name: Commit to repo
        if: github.event_name != 'pull_request'
        run: |
          git add data/live_counts.json
          git ci -m '[ci skip] counter data'
          git pull
          git push
