name: downloads

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch: null

jobs:
  update-counters:
    runs-on: ubuntu-latest
    name: downloads
    steps:
      - name: checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - uses: conda-incubator/setup-miniconda@9f54435e0e72c53962ee863144e47a4b094bfd35 # v2
        with:
          python-version: 3.9
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true
          miniforge-version: latest
          miniforge-variant: Mambaforge

      - name: install deps
        shell: bash -l {0}
        run: |
          mamba install -y -q --file conda-requirements.txt

      - name: run script
        shell: bash -l {0}
        run: |
          python scripts/count_downloads.py

      - name: commit
        if: github.event_name != 'pull_request'
        shell: bash -l {0}
        run: |
          git config --global user.email "79913779+conda-forge-curator[bot]@users.noreply.github.com"
          git config --global user.name "conda-forge-curator[bot]"
          git config --global pull.rebase false

          git pull
          git add data/download_counts.json
          git commit --allow-empty -m '[ci skip] download data'
          for i in `seq 1 10`; do
            git pull
            git push
          done
